### ISSUE TITLE
Bad code.

### ISSUE THREAD

**Issue by Acnologla** [5antos/simpl.db#1]
I believe that this repository should be deleted, or at least a "gore code" warning in its readme.
This code does the exact opposite of what good practice says, and should NOT be used in production.

**Comment by 5antos** [comment]
Could you be more specific, please?

I don't see OOP and FP in the same file at the sime time.
Also, which method, or methods, are you refering to? They all seem pretty correct to me as their methods' names match what they actually do.

**Comment by 5antos** [comment]
I will be closing this issue since there was no fundamental reason for it to be opened at first and you did not provide valid reasons for working on it or even keeping it open.

If you believe that closing this issue was a mistake, please submit a new one with valid arguments and references.
