### ISSUE TITLE
Where data is stored? in 1 file? or other sources

### ISSUE THREAD

**Issue by shidandev** [5antos/simpl.db#15]
May i know, this database can be use for angular app? and where is database save. is it in file.json or just in the indexedDB?

**Comment by 5antos** [comment]
Yes, you can use it in an Angular app. You pretty much can use it in any project that can download packages from the NPM registry (Node.js, Bun, etc.).

The data is stored locally, in JSON files. You can customize where the JSON files are stored.

Feel free to refer to the [documentation](https://simpldb.js.org/getting-started) for more information about that.
